var addBorderPP2=require('./addBorderPP2');
describe('addBorderPP2',function(){
    it("should return correctly", function(){
        expect(addBorderPP2(["abc",
            "ded"])).toEqual(["*****",
            "*abc*",
            "*ded*",
            "*****"]);
        expect(addBorderPP2(["a"])).toEqual(["***",
            "*a*",
            "***"]);
        expect(addBorderPP2(["aa",
            "**",
            "zz"])).toEqual(["****",
            "*aa*",
            "****",
            "*zz*",
            "****"]);
        expect(addBorderPP2(["abcde",
            "fghij",
            "klmno",
            "pqrst",
            "uvwxy"])).toEqual(["*******",
            "*abcde*",
            "*fghij*",
            "*klmno*",
            "*pqrst*",
            "*uvwxy*",
            "*******"]);
        expect(addBorderPP2(["wzy**"])).toEqual(["*******",
            "*wzy***",
            "*******"]);
    });
});
